spring.application.name=movie-booking-system
server.port=8080

# Database configuration placeholders (update with your actual MySQL database credentials)
spring.datasource.url=jdbc:mysql://localhost:3306/movie_booking_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Frontend URL configuration (Vite development server default port)
app.frontend-url=http://localhost:5173

# Spring Mail Configuration (Cập nhật thông tin SMTP để gửi mail thật)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=son666727@gmail.com
spring.mail.password=goctjcveuortcczt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Cloudinary configuration
cloudinary.cloudName=dnjubw5ta
cloudinary.apiKey=935313977588617
cloudinary.apiSecret=n2LnbtZrXnAZdl11u8cvMCyy-F4

# VietQR Payment Configuration (Cập nhật thông tin ngân hàng thực tế của bạn)
vietqr.bankId=MB
vietqr.accountNo=0362490374
vietqr.accountName=HOANG THIEN SON

# PayOS Configuration (Đăng ký miễn phí tại https://payos.vn để lấy 3 mã này)
payos.client-id=ac92ecd5-51ea-482a-afbf-8350a3d26e5d
payos.api-key=aa59791e-37b5-4a65-a013-4044cdb01457
payos.checksum-key=f93a6f4aa096ae299b60a782c0e1f1bdd0ef9fd8e4a04c36a76010b789b8a8a0
